name: Ubuntu 20.04.2 LTS

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: cd docker/ubuntu_20042_lts && docker build . --tag ubuntu_20042_lts:$(date +%s)
